-- ============================================
-- SITE PRINCIPAL : Création utilisateur
-- ============================================
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER ESHOP_MAIN IDENTIFIED BY "Eshop1234"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO ESHOP_MAIN;
GRANT CREATE DATABASE LINK TO ESHOP_MAIN;
GRANT CREATE VIEW TO ESHOP_MAIN;
GRANT CREATE PROCEDURE TO ESHOP_MAIN;
GRANT CREATE TRIGGER TO ESHOP_MAIN;
GRANT CREATE MATERIALIZED VIEW TO ESHOP_MAIN;
GRANT UNLIMITED TABLESPACE TO ESHOP_MAIN;

-- ============================================
-- Création des tables (schéma global complet)
-- ============================================
CREATE TABLE ESHOP_MAIN.CLIENTS (
    IDCLIENT        NUMBER          PRIMARY KEY,
    CODECLIENT      VARCHAR2(100),
    SOCIETE         VARCHAR2(100)   NOT NULL,
    CONTACT         VARCHAR2(100)   NOT NULL,
    FONCTION        VARCHAR2(50)    NOT NULL,
    ADRESSE         VARCHAR2(200),
    VILLE           VARCHAR2(50),
    NAISSANCE       DATE,
    REGION          VARCHAR2(50),
    CODE_POSTAL     VARCHAR2(10),
    PAYS            VARCHAR2(50),
    TELEPHONE       VARCHAR2(20),
    FAX             VARCHAR2(20)
);

CREATE TABLE ESHOP_MAIN.EMPLOYES (
    IDEMPLOYE           NUMBER          PRIMARY KEY,
    NOM                 VARCHAR2(50),
    PRENOM              VARCHAR2(50),
    FONCTIONEMPLOYE     VARCHAR2(200),
    TITREDECOURTOISIE   VARCHAR2(20),
    DATEDENAISSANCE     DATE,
    DATEEMBAUCHE        DATE,
    ADRESSEEMPLOYE      VARCHAR2(200),
    VILLEEMPLOYE        VARCHAR2(50),
    PAYSEMPLOYE         VARCHAR2(50),
    TELDOMICILE         VARCHAR2(20)
);

CREATE TABLE ESHOP_MAIN.FOURNISSEURS (
    IDFOURNISSEUR   NUMBER          PRIMARY KEY,
    SOCIETEFOUR     VARCHAR2(100),
    CONTACTFOUR     VARCHAR2(100),
    FONCTIONFOUR    VARCHAR2(50),
    ADRESSEFOUR     VARCHAR2(200),
    VILLEFOUR       VARCHAR2(50),
    REGIONFOUR      VARCHAR2(50),
    CP              VARCHAR2(10),
    PAYSFOUR        VARCHAR2(50),
    TELFOUR         VARCHAR2(20),
    FAXFOUR         VARCHAR2(20)
);

CREATE TABLE ESHOP_MAIN.CATEGORIE (
    IDCATEG             NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMDECATEGORIE      VARCHAR2(100),
    DESCRIPTION         CLOB
);

CREATE TABLE ESHOP_MAIN.PRODUITS (
    IDPRODUIT                   NUMBER          PRIMARY KEY,
    DESIGNATION                 VARCHAR2(200),
    IDFOUR                      NUMBER,
    IDCATEG                     NUMBER,
    PRIXUNITAIRE                NUMBER(10,2),
    UNITESENSTOCK               NUMBER,
    UNITESCOMMANDEES            NUMBER,
    NIVEAUREAPPROVISIONNEMENT   NUMBER,
    INDISPONIBLE                NUMBER(1)       DEFAULT 0,
    CONSTRAINT fk_prod_four     FOREIGN KEY (IDFOUR)    REFERENCES ESHOP_MAIN.FOURNISSEURS(IDFOURNISSEUR),
    CONSTRAINT fk_prod_categ    FOREIGN KEY (IDCATEG)   REFERENCES ESHOP_MAIN.CATEGORIE(IDCATEG)
);

CREATE TABLE ESHOP_MAIN.COMMANDES (
    IDCOMMANDE      NUMBER          PRIMARY KEY,
    IDCLIENT        NUMBER,
    IDEMPLOYE       NUMBER,
    DATECOMMANDE    DATE,
    DATELIVRAISON   DATE,
    ALIVRERAVANT    DATE,
    NMESSAGER       NUMBER(4),
    PORTNUMBER      NUMBER(4),
    CONSTRAINT fk_cmd_client    FOREIGN KEY (IDCLIENT)  REFERENCES ESHOP_MAIN.CLIENTS(IDCLIENT),
    CONSTRAINT fk_cmd_employe   FOREIGN KEY (IDEMPLOYE) REFERENCES ESHOP_MAIN.EMPLOYES(IDEMPLOYE),
    CONSTRAINT chk_livraison    CHECK (ALIVRERAVANT > DATECOMMANDE)
);

CREATE TABLE ESHOP_MAIN.LIGNECOMMANDES (
    IDLIGNECOMMANDE NUMBER          PRIMARY KEY,
    IDCOMMANDE      NUMBER,
    IDPRODUIT       NUMBER,
    QUANTITE        NUMBER,
    REMISE          NUMBER(5,2),
    CONSTRAINT fk_lc_commande   FOREIGN KEY (IDCOMMANDE)    REFERENCES ESHOP_MAIN.COMMANDES(IDCOMMANDE),
    CONSTRAINT fk_lc_produit    FOREIGN KEY (IDPRODUIT)     REFERENCES ESHOP_MAIN.PRODUITS(IDPRODUIT)
);

COMMIT;

-- ============================================
-- DATABASE LINKS VERS LES SITES DISTANTS
-- ============================================
CREATE DATABASE LINK site1_link
CONNECT TO ESHOP_SITE1 IDENTIFIED BY "Eshop1234"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle-site1)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))';

CREATE DATABASE LINK site2_link
CONNECT TO ESHOP_SITE2 IDENTIFIED BY "Eshop1234"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle-site2)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))';
