-- ============================================
-- SITE 2 : Création utilisateur
-- ============================================
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER ESHOP_SITE2 IDENTIFIED BY "Eshop1234"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO ESHOP_SITE2;
GRANT CREATE DATABASE LINK TO ESHOP_SITE2;
GRANT CREATE VIEW TO ESHOP_SITE2;
GRANT CREATE PROCEDURE TO ESHOP_SITE2;
GRANT CREATE TRIGGER TO ESHOP_SITE2;
GRANT UNLIMITED TABLESPACE TO ESHOP_SITE2;

-- ============================================
-- Tables fragmentées
-- ============================================
CREATE TABLE ESHOP_SITE2.CLIENTS2 (
    IDCLIENT        NUMBER          PRIMARY KEY,
    CODECLIENT      VARCHAR2(100),
    SOCIETE         VARCHAR2(100)   NOT NULL,
    CONTACT         VARCHAR2(100)   NOT NULL,
    FONCTION        VARCHAR2(50)    NOT NULL,
    ADRESSE         VARCHAR2(200),
    VILLE           VARCHAR2(50),
    NAISSANCE       DATE,
    REGION          VARCHAR2(50),
    CODE_POSTAL     VARCHAR2(10),
    PAYS            VARCHAR2(50),
    TELEPHONE       VARCHAR2(20),
    FAX             VARCHAR2(20)
);

CREATE TABLE ESHOP_SITE2.EMPLOYES2 (
    IDEMPLOYE           NUMBER          PRIMARY KEY,
    NOM                 VARCHAR2(50),
    PRENOM              VARCHAR2(50),
    FONCTIONEMPLOYE     VARCHAR2(200),
    TITREDECOURTOISIE   VARCHAR2(20),
    DATEDENAISSANCE     DATE,
    DATEEMBAUCHE        DATE,
    ADRESSEEMPLOYE      VARCHAR2(200),
    VILLEEMPLOYE        VARCHAR2(50),
    PAYSEMPLOYE         VARCHAR2(50),
    TELDOMICILE         VARCHAR2(20)
);

CREATE TABLE ESHOP_SITE2.FOURNISSEURS2 (
    IDFOURNISSEUR   NUMBER          PRIMARY KEY,
    SOCIETEFOUR     VARCHAR2(100),
    CONTACTFOUR     VARCHAR2(100),
    FONCTIONFOUR    VARCHAR2(50),
    ADRESSEFOUR     VARCHAR2(200),
    VILLEFOUR       VARCHAR2(50),
    REGIONFOUR      VARCHAR2(50),
    CP              VARCHAR2(10),
    PAYSFOUR        VARCHAR2(50),
    TELFOUR         VARCHAR2(20),
    FAXFOUR         VARCHAR2(20)
);

CREATE TABLE ESHOP_SITE2.CATEGORIE2 (
    IDCATEG             NUMBER          PRIMARY KEY,
    NOMDECATEGORIE      VARCHAR2(100),
    DESCRIPTION         CLOB
);

CREATE TABLE ESHOP_SITE2.PRODUITS2 (
    IDPRODUIT       NUMBER          PRIMARY KEY,
    DESIGNATION     VARCHAR2(200),
    IDCATEG         NUMBER,
    PRIXUNITAIRE    NUMBER(10,2),
    CONSTRAINT fk_p2_categ FOREIGN KEY (IDCATEG) REFERENCES ESHOP_SITE2.CATEGORIE2(IDCATEG)
);

CREATE TABLE ESHOP_SITE2.COMMANDES2 (
    IDCOMMANDE      NUMBER          PRIMARY KEY,
    IDCLIENT        NUMBER,
    IDEMPLOYE       NUMBER,
    DATECOMMANDE    DATE,
    DATELIVRAISON   DATE,
    ALIVRERAVANT    DATE,
    NMESSAGER       NUMBER(4),          -- ← ajouté
    PORTNUMBER      NUMBER(4),          -- ← ajouté
    CONSTRAINT fk_c2_client  FOREIGN KEY (IDCLIENT)  REFERENCES ESHOP_SITE2.CLIENTS2(IDCLIENT),
    CONSTRAINT fk_c2_employe FOREIGN KEY (IDEMPLOYE) REFERENCES ESHOP_SITE2.EMPLOYES2(IDEMPLOYE),
    CONSTRAINT chk_liv2      CHECK (ALIVRERAVANT > DATECOMMANDE)
);

-- Fragment principal : seulement les petites commandes
CREATE TABLE ESHOP_SITE2.LIGNECOMMANDES2 (
    IDLIGNECOMMANDE NUMBER          PRIMARY KEY,
    IDCOMMANDE      NUMBER,
    IDPRODUIT       NUMBER,
    QUANTITE        NUMBER          CHECK (QUANTITE < 100),  -- critère fragment
    REMISE          NUMBER(5,2),
    CONSTRAINT fk_lc2_cmd  FOREIGN KEY (IDCOMMANDE) REFERENCES ESHOP_SITE2.COMMANDES2(IDCOMMANDE),
    CONSTRAINT fk_lc2_prod FOREIGN KEY (IDPRODUIT)  REFERENCES ESHOP_SITE2.PRODUITS2(IDPRODUIT)
);

COMMIT;

-- ============================================
-- DATABASE LINKS
-- ============================================
CREATE DATABASE LINK main_link
CONNECT TO ESHOP_MAIN IDENTIFIED BY "Eshop1234"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle-main)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))';

CREATE DATABASE LINK site1_link
CONNECT TO ESHOP_SITE1 IDENTIFIED BY "Eshop1234"
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle-site1)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))';
